name: Bug report
about: Create a report to help us improve Shoply
labels: bug

title: "[Bug]: <short description>"
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: Describe the steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: iOS/Android/Web, device/emulator, backend URL
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
