name: Feature request
about: Suggest an idea for Shoply
labels: enhancement

title: "[Feature]: <short description>"
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: What problem are you trying to solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: What would you like to see?
  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: Any risks, alternatives, or examples?