name: Build and Publish Backend Docker Image

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/backend_docker.yml"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/shoply-backend:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/shoply-backend:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/shoply-backend:cache,mode=max
