name: Build Android APK

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
      - ".github/workflows/build_apk.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build APK
        working-directory: app
        env:
          SHOPLY_API_BASE: ${{ secrets.SHOPLY_API_BASE }}
        run: |
          flutter create .
          flutter pub get
          flutter build apk --release --dart-define=SHOPLY_API_BASE=${SHOPLY_API_BASE}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: shoply-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
